name: Build N1

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Package Armvirt as OpenWrt
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMVIRT: 1
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: 5.15.30
          
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: N1_firmware
          path: ${{ env.PACKAGED_OUTPUTPATH }}
